### ISSUE TITLE
Use htmlparser-2 instead of parse5

### ISSUE THREAD

**Issue by yyx990803** [Q42/vue-multi-loader#1]
It seems parse5 is no longer actively maintained, while [htmlparser-2](https://github.com/fb55/htmlparser2) is, and is now the parser used in jsdom.

htmlparser-2 is also faster and more forgiving. I've noticed that parse5 fails at parsing irregular attribute names, e.g. ones that start with `$`.

**Comment by yyx990803** [comment]
Ah, the easier way to do it is just use the htmlparser2 TreeAdapter:

``` js
var parser = new parse5.Parser(parse5.TreeAdapters.htmlparser2, { locationInfo: true });
```

This results in slightly different tree format (`nodeName => name, attrs => attribs`, etc), but it is trivial to adapt to, and this fixes the parsing of attributes like `$data`.

**Comment by inikulin** [comment]
parse5 is still actively maintained actually, it's just don't have many things left to implement. jsdom uses parse5 BTW.
