### ISSUE TITLE
Add peer dependencies

### ISSUE THREAD

**Issue by yyx990803** [Q42/vue-multi-loader#2]
So regardless of the loader setup we will need `html-loader`, `style-loader` and `css-loader` to build properly. It might be a good idea to add them as peer dependencies.

**Comment by yyx990803** [comment]
See #3.

Btw, I really like the implementation and think it should replace the default `vue-loader`. It would be great if we can move this to `vuejs/vue-loader` and maintain it over there as the official loader, but I also totally respect it if you'd like to keep it as a separate, personal project. Let me know :)

**Comment by sjoerdvisscher** [comment]
I think it would be awesome if vue-multi-loader would become the official loader! I think you can just fork, or do I need to do something else?

**Comment by yyx990803** [comment]
Yeah, I can fork it to `vuejs/vue-loader`. Thanks for the great work!
